In [1]:
# 2.1

In [ ]:
import torch

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [31]:
X = x.reshape(3,4)
print(X)
print(X)
X  # 因为交互环境的“自动输出最后一个表达式”功能

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [32]:
X = x.reshape(3,4)
X  #所以这里就不输出了
print(X)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
x,X

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [19]:
X = torch.arange(12,dtype = float).reshape((3,4))   #和reshape(3,4)效果一样
Y = torch.tensor([[1,2,3,4],[2,1,4,3],[4,3,2,1]])
X,Y,X == Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]], dtype=torch.float64),
 tensor([[1, 2, 3, 4],
         [2, 1, 4, 3],
         [4, 3, 2, 1]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [14]:
A = X.numpy()
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [15]:
B = torch.Tensor(A)
B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [20]:
# 2.1练习
Y > X

tensor([[ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [33]:
# 2.2

In [42]:
import os

os.makedirs(os.path.join('.','data'),exist_ok = True)
data_file = os.path.join('.','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [43]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [44]:
data

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [53]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       NaN        True      False
1       2.0       False       True
2       4.0       False       True
3       NaN       False       True
   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

In [54]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True,dtype = int)
print(inputs)
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       NaN           1          0
1       2.0           0          1
2       4.0           0          1
3       NaN           0          1
   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [57]:
# 2.2练习
import pandas as pd
import os

data_file2 = os.path.join('.','data','house_tiny2.csv')
with open(data_file2,'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,147500\n')
    f.write('5,NA,195070\n')
    f.write('7,NA,214500\n')

In [60]:
data2 = pd.read_csv(data_file2)
data2

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  147500
4       5.0   NaN  195070
5       7.0   NaN  214500

In [62]:
data2.drop(index = 3)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
4       5.0   NaN  195070
5       7.0   NaN  214500

In [64]:
inputs, outputs = data2.iloc[:, 0:2], data2.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True,dtype = int)
print(inputs)
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       NaN           1          0
1       2.0           0          1
2       4.0           0          1
3       NaN           0          1
4       5.0           0          1
5       7.0           0          1
   NumRooms  Alley_Pave  Alley_nan
0       4.5           1          0
1       2.0           0          1
2       4.0           0          1
3       4.5           0          1
4       5.0           0          1
5       7.0           0          1

In [65]:
data2.iloc[:, 0:2]

   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN
4       5.0   NaN
5       7.0   NaN

In [67]:
# 2.3

In [68]:
x = torch.arange(4,dtype = torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [71]:
A = torch.arange(20,dtype = torch.float32).reshape(5,4)
A.shape,A.sum()

(torch.Size([5, 4]), tensor(190.))

In [72]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [73]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1,A_sum_axis0.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([4]))

In [75]:
# torch.dot(a,b)
# torch.mv(A,x)
# torch.mm(A,B)
# torch.norm(u)  #L2范数
# torch.abs(u).sum()  #L1范数

In [85]:
# 2.3练习
x = torch.zeros((2,3,4))
print(len(x))
x

2

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [86]:
x = torch.zeros((2,3,4,5))
print(len(x))
x

2

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])

In [89]:
A = torch.arange(20,dtype = float).reshape(5,4)
print(A)
A/A.sum(axis=1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=torch.float64)

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

In [91]:
torch.linalg.norm(torch.rand(3,4))

tensor(1.5188)

In [94]:
torch.linalg.norm(torch.ones((3,4)))  #根号12

tensor(3.4641)

In [95]:
torch.linalg.norm(torch.ones((3,4,5)))  #根号60

tensor(7.7460)

In [96]:
torch.norm(torch.ones((3,4,5)))  #根号60

tensor(7.7460)